apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recipe-detection.fullname" . }}-config
  labels:
    {{- include "recipe-detection.labels" . | nindent 4 }}
data:
  chart-version: {{ .Values.recipeData.chartVersion | quote }}
  recipe-data.json: |
    {{- $data := dict
        "chartVersion" .Values.recipeData.chartVersion
        "catalog_name" (default "" .Values.recipeData.catalog_name)
        "catalog_description" (default "" .Values.recipeData.catalog_description)
        "release_date" (default "" .Values.recipeData.release_date)
        "catalog_status" (default "" .Values.recipeData.catalog_status)
        "maintainer" (default "" .Values.recipeData.maintainer)
        "recipes" .Values.recipeData.recipes
      }}
    {{ $data | toJson | nindent 4 }}
