recipeData:
  chartVersion: 1.3.2
  target_cluster: prod
  catalog_name: HPE Analytics
  catalog_description: Streaming perform catalog
  release_date: '2026-06-08'
  catalog_status: GA
  maintainer: HPE Devops Team
  values_file: hello.yaml
  recipes:
  - version: 1.3.1
    description: nginx-web-server
    release_date: '2026-06-08'
    status: GA
    release_notes: web server
    components:
      nginx:
        version: 1.25.5
        release_date: '2026-06-08'
        upgrade_from:
        - 1.25.4
        upgrade_to:
        - 1.25.5
      ingress-controller:
        version: 4.10.0
        release_date: '2026-06-08'
        upgrade_from:
        - 4.9.1
        upgrade_to:
        - 4.10.0
      redis:
        version: 7.4.0
        release_date: '2026-06-08'
        upgrade_from:
        - 7.2.5
        upgrade_to:
        - 7.4.0
      fluent-bit:
        version: 3.1.2
        release_date: '2026-06-08'
        upgrade_from:
        - 3.1.0
        upgrade_to:
        - 3.1.2
    upgrade_to:
    - 1.3.2
