recipeData:
  chartVersion: 9.0.1
  catalog_name: HPE Analytics
  catalog_description: Enterprise Analytics
  catalog_status: GA
  maintainer: HPE Devops team
  recipes:
  - version: 1.4.0
    description: Major feature and stability update
    release_date: '2026-06-04'
    status: GA
    release_notes: Upgraded all core platform services to latest supported versions
    components:
      analytics-engine:
        version: 1.2.1
        release_date: '2026-06-03'
        upgrade_from:
        - 1.1.1
        upgrade_to:
        - 1.3.1
      postgres-db:
        version: 1.2.3
        release_date: '2026-06-03'
        upgrade_from:
        - 1.1.3
        upgrade_to:
        - 1.4.1
      stream-processor:
        version: 1.2.2
        release_date: '2026-06-03'
        upgrade_from:
        - 1.1.2
        upgrade_to:
        - 1.3.2
        - 1.4.2
    upgrade_to:
    - 1.4.1
    upgrade_from:
    - 1.3.9
