recipeData:
  chartVersion: 0.0.1
  recipes:
  - version: 1.3.0
    description: Base recipe with core analytics components
    components:
      airflow: 2.3.0
      hbase: 2.4.6
      kafka: 3.1.0
      spark: 3.1.2
    upgradePaths: [
      ]
  - version: 1.3.1
    description: Patch release with minor component upgrades
    components:
      airflow: 2.4.1
      hbase: 2.4.8
      kafka: 3.2.1
      spark: 3.2.0
    upgradePaths:
    - 1.3.0
