recipeData:
  chartVersion: 9.0.7
  target_cluster: dev
  catalog_name: HPE analytics runtime
  catalog_description: okkkk
  release_date: '2026-06-08'
  catalog_status: GA
  maintainer: HPE Devops Team
  values_file: values-v9.0.7.yaml
  recipes:
  - version: 1.3.2
    description: fine
    release_date: '2026-06-17'
    status: GA
    release_notes: hello
    components:
      kafka:
        version: 3.0.2
        release_date: '2026-06-02'
        upgrade_from:
        - 3.0.1
        upgrade_to:
        - 3.0.3
    upgrade_to:
    - 1.3.3
    upgrade_from:
    - 1.3.1
