recipeData:
  chartVersion: 9.0.5
  target_cluster: dev
  catalog_name: HPE Alletra MP Block
  catalog_description: Major analytics platform upgrade
  release_date: '2026-06-10'
  catalog_status: GA
  maintainer: HPE Devops Team
  values_file: values-v9.0.5.yaml
  recipes:
  - version: 1.5.1
    description: HPE Alletra MP Block baseline release
    release_date: '2026-06-10'
    status: GA
    release_notes: ESXi 7U3, Gen10 SPP, Block Storage OS 10.4.8
    components:
      hypervisor:
        version: 7.0.3-24411414
        release_date: '2026-05-10'
        upgrade_from:
        - 7.0.3-23794027
        - 7.0.3-23307199
        upgrade_to:
        - 8.0.3-24859861
      server_firmware:
        version: 2025.01.00.00
        release_date: '2026-04-07'
        upgrade_from:
        - 2024.11.00.00
        - 2024.09.00.00
        upgrade_to:
        - 2025.11.00.00
      storage_operating_system:
        version: 10.4.8
        release_date: '2026-04-07'
        upgrade_from:
        - 10.4.6
        - 10.4.5
        - 10.4.2
        upgrade_to: []
    upgrade_to:
    - 1.5.2
  - version: 1.5.2
    description: HPE Alletra MP Block platform upgrade
    release_date: '2026-04-15'
    status: GA
    release_notes: ESXi 8U3, Gen10 SPP 2025.11, storage OS unchanged
    components:
      hypervisor:
        version: 8.0.3-24859861
        release_date: '2026-06-08'
        upgrade_from:
        - 7.0.3-24411414
        - 8.0.3-24784735
        upgrade_to: []
      server_firmware:
        version: 2025.11.00.00
        release_date: '2026-06-08'
        upgrade_from:
        - 2025.01.00.00
        - 2024.11.00.00
        upgrade_to: []
      storage_operating_system:
        version: 10.4.8
        release_date: '2026-04-22'
        upgrade_from:
        - 10.4.6
        - 10.4.5
        upgrade_to: []
    upgrade_from:
    - 1.5.1
