recipeData:
  chartVersion: 2.2.3
  recipes:
  - version: 1.3.5
    description: test1
    components:
      dhoni:
        version: 3.6.2
        upgrade_from: []
        upgrade_to:
        - 4.7.2
      kafka:
        version: 2.6.2
        upgrade_from:
        - 3.2.3
        - 4.7.2
        upgrade_to: []
      spark:
        version: 3.5.2
        upgrade_from:
        - 3.6.4
        upgrade_to:
        - 4.7.2
        - 4.5.6
    upgradePaths: [
      ]
